plugins {
    id 'java'
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'edu.sc.seis.launch4j' version '4.0.0'
}

javafx {
    version = "27"
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.media']
}

group = 'com.project'
version = '1.0'
def appName = 'Bubble Shooter'
description = appName

tasks.withType(JavaCompile) { options.encoding = 'UTF-8' }

repositories {
    mavenLocal()
    mavenCentral()
}

java {
    sourceCompatibility = '25'
    targetCompatibility = '25'
}

application { mainClass = 'com.piotrek.main.Main' }

clean.doLast { ['target', "${appName}.exe"].collect { file it }.each { it.isDirectory() ? it.deleteDir() : it.delete() } }

run { jvmArgs '--enable-native-access=javafx.graphics,javafx.media' }

jar {
    archiveBaseName = "${appName}.jar"
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest { attributes "Main-Class": application.mainClass }
    from { configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }
}

createExe {
    headerType = 'gui'
    outputDir = '/'
    outfile = "${appName}.exe"
    libraryDir = 'build/libs'
    dontWrapJar = true
    errTitle = 'Error'
    downloadUrl = 'https://www.oracle.com/java/technologies/downloads/'
    icon = "$project.rootDir/icon.ico"
    jreMinVersion = '25'
    bundledJrePath = '%JAVA_HOME%'
    jarTask = jar
    doLast { ant.move file: "$layout.buildDirectory.orNull/${appName}.exe", todir: project.rootDir }
}